[workspace]
members = [
    "crates/collection",
    "crates/collections_panel_ui",
    "crates/environment",
    "crates/keybindings_service",
    "crates/preferences",
    "crates/request",
    "crates/theme",
    "crates/updater",
    "crates/workspace",
    "crates/settings_ui",
    "crates/tab_ui",
    "crates/request-eagle",
]
resolver = "3"

[workspace.dependencies]
anyhow = "1"
gpui-kit = { version = "=0.6.2", default-features = false }
# Match GPUI Kit's HTTP client version to keep the GPUI HTTP traits compatible.
reqwest_client = { package = "gpui-pre-reqwest-client", version = "=0.3.5" }
thiserror = "2"
