id = "editor-variables-demo"
name = "Editor variables"
schema_version = 1

[request]
type = "http"
method = "POST"
path = "{{base_url}}/echo"
headers = [[
    "{{header_name}}",
    "{{message}}",
]]
body = [123, 10,
    32,
    32,
    34,
    109,
    101,
    115,
    115,
    97,
    103,
    101,
    34,
    58,
    32,
    34,
    123,
    123,
    109,
    101,
    115,
    115,
    97,
    103,
    101,
    125,
    125,
    34,
    44,
    10,
    32,
    32,
    34,
    105,
    100,
    34,
    58,
    32,
    34,
    123,
    123,
    36,
    103,
    117,
    105,
    100,
    125,
    125,
    34,
    44,
    10,
    32,
    32,
    34,
    116,
    105,
    109,
    101,
    34,
    58,
    32,
    34,
    123,
    123,
    36,
    105,
    115,
    111,
    84,
    105,
    109,
    101,
    115,
    116,
    97,
    109,
    112,
    125,
    125,
    34,
    10,
    125]
query = [[
    "{{query_name}}",
    "{{$timestamp}}",
]]
