[package]
name = "settings_ui"
version = "0.1.0"
edition = "2024"

[dependencies]
gpui-kit = { workspace = true, features = ["component"] }
keybindings_service = { path = "../keybindings_service" }
preferences = { path = "../preferences" }
request_eagle_theme = { package = "theme", path = "../theme" }
updater = { path = "../updater" }

[dev-dependencies]
gpui-kit = { workspace = true, features = ["test-support"] }
serde_json = "1"
smol = "2"
tempfile = "3"
