[package]
name = "request-eagle-cli"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
anyhow.workspace = true
base64 = "0.22"
clap = { version = "4", features = ["derive", "string"] }
collection = { path = "../collection" }
dirs = "6"
environment = { path = "../environment" }
futures = "0.3"
preferences = { path = "../preferences", default-features = false }
request = { path = "../request" }
schemars = "1"
serde = { version = "1", features = ["derive"] }
smol = "2"
serde_json = "1"

[dev-dependencies]
rcgen = { version = "0.14", default-features = false, features = ["pem", "ring"] }
tempfile = "3"
