[package]
name = "script_intelligence"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
anyhow.workspace = true
event-listener = "5"
flate2 = "1"
futures-channel = "0.3"
lsp-types = "0.97"
request = { path = "../request" }
rquickjs = "0.14"
serde_json = "1"
# Which characters continue a JavaScript identifier.
unicode-ident = "1"

[target.'cfg(all(target_os = "linux", target_env = "gnu"))'.dependencies]
libc = "0.2"

[build-dependencies]
flate2 = "1"
rquickjs = "0.14"

[dev-dependencies]
smol = "2"
