[package]
name = "workspace"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["clock"] }
environment = { path = "../environment" }
collection = { path = "../collection" }
collections_panel_ui = { path = "../collections_panel_ui" }
futures = "0.3"
request = { path = "../request" }
request_history = { package = "history", path = "../history" }
request_eagle_theme = { package = "theme", path = "../theme" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
settings_ui = { path = "../settings_ui" }
tab_ui = { path = "../tab_ui" }
tempfile = "3"
gpui-kit = { workspace = true, features = ["component"] }
preferences = { path = "../preferences" }
keybindings_service = { path = "../keybindings_service" }
updater = { path = "../updater" }

[dev-dependencies]
gpui-kit = { workspace = true, features = ["component", "test-support"] }
